// AUTO-GENERATED by scripts/generate-domain-footprints.ts — do not edit by hand.
// Approximate non-NULL data footprints (closed [lon, lat] rings) for reprojected
// regular-grid domains, so seamless borders follow the real data shape instead of
// the rectangular grid box. Regenerate with: npm run generate:footprints

export const DOMAIN_FOOTPRINTS: Record<string, Array<[number, number]>> = {
	dwd_icon_d2: [
		[-0.32, 43.18],
		[8.64, 43.64],
		[17.64, 43.38],
		[20.34, 57.7],
		[14.54, 58],
		[7.88, 58.06],
		[2.2, 57.86],
		[-3.94, 57.36],
		[-0.32, 43.18]
	],
	meteofrance_arome_france0025: [
		[-8.175, 37.525],
		[-0.2, 38],
		[5.85, 37.95],
		[12.2, 37.525],
		[15.975, 54.7],
		[7.825, 55.275],
		[-0.5, 55.375],
		[-6.25, 55.15],
		[-12, 54.675],
		[-8.175, 37.525]
	]
};

/** Returns the precomputed data-shape outline for a domain, if one exists. */
export const getDomainFootprint = (domainValue: string): Array<[number, number]> | undefined =>
	DOMAIN_FOOTPRINTS[domainValue];
